propagate test failures

diff --git a/test/lib/test-aggregate-results b/test/lib/test-aggregate-results
--- a/test/lib/test-aggregate-results
+++ b/test/lib/test-aggregate-results
@@ -79,3 +79,13 @@ if [ "$skipped" != "0" ]; then
     tests=$(pluralize "test" $skipped)
     echo "$skipped $tests skipped."
 fi
+
+# Note that we currently do not consider skipped tests as failing the
+# build.
+
+if [ $success -gt 0 -a $fixed -eq 0 -a $failed -eq 0 ]
+then
+    exit 0
+else
+    exit 1
+fi
